services:
  app:
    build:
      context: .
      args:
        PHP_VERSION: "8.4"
    image: inventaris:latest
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    ports:
      - "8004:80"

  worker-default:
    build:
      context: .
      args:
        PHP_VERSION: "8.4"
    image: inventaris:latest
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    command: php artisan queue:work

  worker-generate-items:
    build:
      context: .
      args:
        PHP_VERSION: "8.4"
    image: inventaris:latest
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    command: php artisan queue:work --queue=generate-items
