services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: prod
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8004:80"
    volumes:
      - app_code:/var/www
      - storage_data:/var/www/storage

  worker-default:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: prod
    env_file:
      - .env
    command: php artisan queue:work
    volumes:
      - app_code:/var/www
      - storage_data:/var/www/storage

  worker-generate-items:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: prod
    env_file:
      - .env
    command: php artisan queue:work --queue=generate-items
    volumes:
      - app_code:/var/www
      - storage_data:/var/www/storage

volumes:
  app_code:
  storage_data:
